const routes = {
    home: '/',
    blog: '/blog',
    howItWork: '/howItWork',
    findTutor: '/findTutor',
    forStudent: '/forStudent',
    customerSay: '/customerSay',
    profileStudent: '/student/:nickname',
    profileTutor: '/tutor/:nickname',
    requestTutor: '/requestTutor',
    advertisement: '/advertisement',
    onlineTutoring: '/onlineTutoring',
    account: '/:account/:role/:accountName',
    tutorDetail: '/:tutorId',
    registrationTutor1: '/registration/tutor/step1',
    registrationTutor2: '/registration/tutor/step2',
    registrationStudent1: '/registration/student/step1',
    registrationStudent2: '/registration/student/step2',
    aboutUs: '/aboutUs',
    transaction: 'transaction',
    payment: '/transaction/payment',
    history: '/transaction/history',
    learnMore: '/learnMore',
    tipSuccess: '/tipSuccess',
    dashboardTutor: '/dashboardTutor',
    feedbackHistory: '/feedbackHistory',
    unauthorized: '/unauthorized',
    messages: '/messages',
    notification: '/notifications',
    moderator: '/moderator',
    modeClass: '/moderator/maindash',
    classes: '/classes',
};

export default routes;
